# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f323f0ef08b0b0772555281b66fd74830a70f80a5f337ca8bb1903433590a74f5a3f8b85844bf4d7532e44f2810e914f6bf8149c773849010f0df9a0e9af436

test:
  secret_key_base: 744fe4e4899edf8b2f4c5dd040f2bb60b7b86321f4a9034fe4c888b6febc95f178d95f87bc05bff269c83037748761d754a8740c7e29f2991885ceb62e138294

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
